# Generated by Django 3.1.5 on 2021-01-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(max_length=100)),
                ('Duration', models.FloatField()),
            ],
        ),
    ]
